### ISSUE TITLE
have a slightly difference between thumbnail of pictures and videos

### ISSUE THREAD

**Issue by allan-simon** [kivy-garden/garden.filechooserthumbview#3]
maybe it will make it easier for people to differentiate between  images and videos if videos got a little  play button (simple white triangle in a circle with transparency)  like this 
![selection_028](https://f.cloud.github.com/assets/213167/1179447/ca810efc-21d4-11e3-8b42-1a1ec96e30e9.png)

what do you think ?

**Comment by martinsik** [comment]
I checked the code and PIL is used only to overlay the thumbnail image. I think creating overlays is possible also with just `ffmpeg` filters so It would be great if we could get rid of PIL completely. I'll have a look at it and see whether it's even possible.

**Comment by Davideddu** [comment]
Alright, perfect!
On Aug 4, 2015 11:32 AM, Martin Sikora <notifications@github.com> wrote:I checked the code and PIL is used only to overlay the thumbnail image. I think creating overlays is possible also with just ffmpeg filters so It would be great if we could get rid of PIL completely. I'll have a look at it and see whether it's even possible.
